# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Documentation for anipy-cli and anipy-api
site_author: sdaqo
site_description: >-
  This is the full Documentation for the api from anipy-cli and the cli itself.

repo_name: sdaqo/anipy-cli
repo_url: https://github.com/sdaqo/anipy-cli

theme:
  name: material
  logo: /assets/anipy-logo-dark-compact.svg

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - content.tooltips

nav:
  - Home:
    - Index: index.md
    - Availability: availabilty.md
    - Changelog: changelog.md
  - Getting Started - CLI: getting-started-cli/index.md
  - Getting Started - API: 
    - Index: getting-started-api/index.md
    - Examples:
      - 1. Provider: getting-started-api/examples/provider.md
      - 2. Anime: getting-started-api/examples/anime.md
      - 3. Downloader: getting-started-api/examples/downloader.md
      - 4. Player: getting-started-api/examples/player.md
      - 5. MyAnimeList: getting-started-api/examples/myanimelist.md
      - 6. Local List: getting-started-api/examples/locallist.md
  - Contributing: contributing/index.md
  - API Code Reference: reference/

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py  
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [api/src]
          options:
            docstring_options:
                ignore_init_summary: true
            docstring_style: "google"
            merge_init_into_class: true
            allow_inspection: true
            show_source: true

