[tool.poetry]
name = "anipy-cli"
version = "3.0.0"
description = "Little tool in python to watch anime from the terminal (the better way to watch anime)"
authors = ["sdaqo <sdaqo.dev@protonmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/sdaqo/anipy-cli"
keywords = ["anime", "cli"]
readme = "README.md"
non-package = true

[tool.poetry.scripts]
anipy-cli = "anipy_cli.run_anipy_cli:main"

# mkdocs
# mkdocs-material
# mkdocs-gen-files
# mkdocs-literate-nav
# mkdocs-section-index
# mkdocstrings[python]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sdaqo/anipy-cli/issues"
